// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using herlivre_api.Models;

#nullable disable

namespace Herlivre_api.Migrations
{
    [DbContext(typeof(GeralDbContext))]
    partial class GeralDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Herlivre_api.Models.Cargo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Nome")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Cargo");
                });

            modelBuilder.Entity("herlivre_api.Models.Cidade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Continente")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nome")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Pais")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.ToTable("Cidade");
                });

            modelBuilder.Entity("Herlivre_api.Models.Comprovante", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Data_compra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("id_pacote")
                        .HasColumnType("bigint");

                    b.Property<long?>("id_registro_aluguel_quarto")
                        .HasColumnType("bigint");

                    b.Property<long?>("id_usuario")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("id_pacote");

                    b.HasIndex("id_registro_aluguel_quarto");

                    b.HasIndex("id_usuario");

                    b.ToTable("Comprovante");
                });

            modelBuilder.Entity("herlivre_api.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Bairro")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Cafe_manha")
                        .HasColumnType("bit");

                    b.Property<string>("Cep")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Logradouro")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nome")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Qtd_estrelas")
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    b.Property<double>("Valor_min")
                        .HasColumnType("float");

                    b.Property<bool>("Wifi")
                        .HasColumnType("bit");

                    b.Property<long?>("id_cidade")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("id_cidade");

                    b.ToTable("Hotel");
                });

            modelBuilder.Entity("Herlivre_api.Models.Pacote", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Desconto")
                        .HasColumnType("int");

                    b.Property<int>("Total_pessoas")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<double>("Valor_original")
                        .HasColumnType("float");

                    b.Property<double>("Valor_promocional")
                        .HasColumnType("float");

                    b.Property<long?>("id_registro_aluguel_quarto")
                        .HasColumnType("bigint");

                    b.Property<long?>("id_voo_1")
                        .HasColumnType("bigint");

                    b.Property<long?>("id_voo_2")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("id_registro_aluguel_quarto");

                    b.HasIndex("id_voo_1");

                    b.HasIndex("id_voo_2");

                    b.ToTable("Pacote");
                });

            modelBuilder.Entity("Herlivre_api.Models.Quarto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Diaria")
                        .HasColumnType("int");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int>("Qtd_assentos_disp")
                        .HasColumnType("int");

                    b.Property<int>("Qtd_camas")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.Property<int?>("id_hotel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("id_hotel");

                    b.ToTable("Quarto");
                });

            modelBuilder.Entity("Herlivre_api.Models.RegistroAluguelQuarto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Data_entrada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Data_saida")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("id_quarto")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("id_quarto");

                    b.ToTable("Registro_aluguel_quarto");
                });

            modelBuilder.Entity("Herlivre_api.Models.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Cpf")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nome")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("id_cargo")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("id_cargo");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Herlivre_api.Models.Voo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Companhia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Data_chegada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Data_partida")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Local_partida")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Num_assento")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Num_voo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Qtd_assentos_disp")
                        .HasColumnType("int");

                    b.Property<long?>("id_cidade")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("id_cidade");

                    b.ToTable("Voo");
                });

            modelBuilder.Entity("Herlivre_api.Models.Comprovante", b =>
                {
                    b.HasOne("Herlivre_api.Models.Pacote", "Pacote")
                        .WithMany()
                        .HasForeignKey("id_pacote");

                    b.HasOne("Herlivre_api.Models.RegistroAluguelQuarto", "RegistroAluguelQuarto")
                        .WithMany()
                        .HasForeignKey("id_registro_aluguel_quarto");

                    b.HasOne("Herlivre_api.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("id_usuario");

                    b.Navigation("Pacote");

                    b.Navigation("RegistroAluguelQuarto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("herlivre_api.Models.Hotel", b =>
                {
                    b.HasOne("herlivre_api.Models.Cidade", "Cidade")
                        .WithMany()
                        .HasForeignKey("id_cidade");

                    b.Navigation("Cidade");
                });

            modelBuilder.Entity("Herlivre_api.Models.Pacote", b =>
                {
                    b.HasOne("Herlivre_api.Models.RegistroAluguelQuarto", "RegistroAluguelQuarto")
                        .WithMany()
                        .HasForeignKey("id_registro_aluguel_quarto");

                    b.HasOne("Herlivre_api.Models.Voo", "Voo_1")
                        .WithMany()
                        .HasForeignKey("id_voo_1");

                    b.HasOne("Herlivre_api.Models.Voo", "Voo_2")
                        .WithMany()
                        .HasForeignKey("id_voo_2");

                    b.Navigation("RegistroAluguelQuarto");

                    b.Navigation("Voo_1");

                    b.Navigation("Voo_2");
                });

            modelBuilder.Entity("Herlivre_api.Models.Quarto", b =>
                {
                    b.HasOne("herlivre_api.Models.Hotel", "Hotel")
                        .WithMany()
                        .HasForeignKey("id_hotel");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("Herlivre_api.Models.RegistroAluguelQuarto", b =>
                {
                    b.HasOne("Herlivre_api.Models.Quarto", "Quarto")
                        .WithMany()
                        .HasForeignKey("id_quarto");

                    b.Navigation("Quarto");
                });

            modelBuilder.Entity("Herlivre_api.Models.Usuario", b =>
                {
                    b.HasOne("Herlivre_api.Models.Cargo", "Cargo")
                        .WithMany()
                        .HasForeignKey("id_cargo");

                    b.Navigation("Cargo");
                });

            modelBuilder.Entity("Herlivre_api.Models.Voo", b =>
                {
                    b.HasOne("herlivre_api.Models.Cidade", "Cidade")
                        .WithMany()
                        .HasForeignKey("id_cidade");

                    b.Navigation("Cidade");
                });
#pragma warning restore 612, 618
        }
    }
}
